### PR TITLE
Add BTC21 token f6b71e38e0a3b0ddac0b8292f6cf11496da0bbf4178a443a3f67adef177e2fae  (#401)

### PR DESCRIPTION
**Pull request by sherkitty**
Please update Token Icons
Alternatively, you could create simple server-side web script that allows token creators to submit their icons via upload option. The upload request should require token creators to send a validation deposit of 0.001 units from their first genesis address.

### CODE REVIEW

**Comment by kosinusbch** [comment]
Hey @sherkitty, could you give some context as to what this token is, and why it needs to use the BTC logo?

**Comment by sherkitty** [comment]
I think if you notice, there is a very distinct
'21', at the bottom right-hand corner of the logo.   The original logo has clearly been altered.  While it has some resembĺence to BTC, the 21 on the logo and the symbol "BTC21" are clearly not the same.
  
Another coin ( Not sure if it's 1 or 2 other tokens) have used the unaltered symbol of BTC, so I think you should remove their logo(s) from your registry.

The purpose of the token...
To be honest, I am not exactly certain yet.  

I am considering building a cryptographic bridge i.e BCH > SLP > ETH > BTC and vice versa; however, after looking at wormhole, I think they beat me to the punch.  I just briefly looked at press release today indicating that the wormhole project might have already accomplished what I was planning to do.

In the spirit of decentralization, I think it would the best to allow token creators to upload their own logo via a Web interface, as previously described.   If there is a valid DCMA complaint, of clearly fraudulent misuse of another registered party(s) logo with symbol, then remove any such logo and replace it with a "copyright fraud" logo; otherwise, token creators have to wait on you to allow a pull request so their logo can be added.  This is both time consuming and inefficient.  


⁣Get BlueMail for Android ​

**Comment by kosinusbch** [comment]
Sounds good, just ideally wanna avoid people using the endpoint to scam newbies. We don't really care about DMCA, you can upload whatever copyrighted material you want :)

**Comment by sherkitty** [comment]
I want to run my own bitcoin cash full node with SLP.  I can't find anywhere in the code where the url tokens.bch.sx exists.  Technically speaking, shouldn't I be allowed to host my own icons by soft-forking the code that points to tokens.bch.sx.   In the spirit of decentralization, could you please tell me which line of code that I would have to modify?
⁣Get BlueMail for Android ​

**Comment by sherkitty** [comment]
Could you please provide a forward-looking statement as to when this task will be completed, or should your manual oversight of curating the icon collection be considered "depreciated".  I think you should go to the decentralized route and let people host their own token icons. and let each server run a full node.  
⁣Get BlueMail for Android ​

**Pull request merged**
