### PR TITLE
add token slp

### PR DESCRIPTION
**Pull request by momo166**
add token slp

### CODE REVIEW

**Comment by rpgamer107** [comment]
original 88552a4e4fdc49426919e4397b5ec465a00941d1f9bc657437d9aeb8350dce40

**Comment by rpgamer107** [comment]
128 88552a4e4fdc49426919e4397b5ec465a00941d1f9bc657437d9aeb8350dce40

**Comment by rpgamer107** [comment]
64 88552a4e4fdc49426919e4397b5ec465a00941d1f9bc657437d9aeb8350dce40

**Comment by rpgamer107** [comment]
32 88552a4e4fdc49426919e4397b5ec465a00941d1f9bc657437d9aeb8350dce40

**Review by rpgamer107 — APPROVED** [review]
NextGen AIO

**Comment by rpgamer107** [comment]
NextGen AIO

**Comment by kosinusbch** [comment]
@rpgamer107 You'll need to submit those icons in a PR like the guy above did.

Essentially just:
1) click "fork" on the main repository, go to your profile
2) Go to the /128/ folder, click "upload file", repeat
3) Come back here and press "submit pull request" once all the icons are uploaded

**Review by rpgamer107 — COMMENTED** [review]
[https://nextgenaio.com](url)

**Pull request merged**
