### PR TITLE
DIGM Token

### PR DESCRIPTION
**Pull request by aejontargaryen**
`8261c44c396fb1120b699b10de708f37a72f8b0339752d4dba67e193dbf898eb`

### CODE REVIEW

**Comment by aejontargaryen** [comment]
In case these would work better http://tokens.bitcoin.com/32/8261c44c396fb1120b699b10de708f37a72f8b0339752d4dba67e193dbf898eb.png

http://tokens.bitcoin.com/64/8261c44c396fb1120b699b10de708f37a72f8b0339752d4dba67e193dbf898eb.png

http://tokens.bitcoin.com/128/8261c44c396fb1120b699b10de708f37a72f8b0339752d4dba67e193dbf898eb.png

**Comment by aejontargaryen** [comment]
Hi. Have I overlooked something necessary for PR to be merged?
@blockparty-sh @kosinusbch

**Comment by kosinusbch** [comment]
Hey, sorry for the delay. The file in the 'original' icon doesn't appear to be in the correct aspect ratio (1:1), do you think you could update it?

**Comment by aejontargaryen** [comment]
Been afk for a piece.
Think I can do this on mobile tho.

**Pull request closed without merging**
