### PR TITLE
Adding Icons & svg Icon for TASK (TSK) TOKEN

### PR DESCRIPTION
**Pull request by hubbytuby**
Adding Icons, Logos for TSK TOKEN kindly accept my pull request and merge my Icons to the original repository.

### CODE REVIEW

**Comment by kosinusbch** [comment]
Hey @hubbytuby, the icons need to be formatted as PNG's, not as JPG's

**Comment by hubbytuby** [comment]
ok will update

**Comment by hubbytuby** [comment]
thanks

**Comment by hubbytuby** [comment]
All the logos updated from .jpg to .png

**Comment by blockparty-sh** [comment]
The jpgs are still in this, recommend you create new pr with just png files, thanks.

**Pull request closed without merging**
