### PR TITLE
Add Weltoken Icons

### PR DESCRIPTION
**Pull request by hafeni212**
bfb634915f51d2e649d43537a3d5d959d185952c547a86cd7185b1dd1d7091a9.png
bfb634915f51d2e649d43537a3d5d959d185952c547a86cd7185b1dd1d7091a9

### CODE REVIEW

**Comment by hafeni212** [comment]
https://tokens.bch.sx/64/bfb634915f51d2e649d43537a3d5d959d185952c547a86cd7185b1dd1d7091a9.png
bfb634915f51d2e649d43537a3d5d959d185952c547a86cd7185b1dd1d7091a9

**Comment by hafeni212** [comment]
https://tokens.bch.sx/128/bfb634915f51d2e649d43537a3d5d959d185952c547a86cd7185b1dd1d7091a9.png
bfb634915f51d2e649d43537a3d5d959d185952c547a86cd7185b1dd1d7091a9

**Comment by hafeni212** [comment]
https://tokens.bch.sx/original/bfb634915f51d2e649d43537a3d5d959d185952c547a86cd7185b1dd1d7091a9.png
bfb634915f51d2e649d43537a3d5d959d185952c547a86cd7185b1dd1d7091a9

**Comment by kosinusbch** [comment]
You didn't add any valid files to the actual repo. Images don't automatically get put in the PR because you post them in the public comment section

Will close for now for organizational reasons, but if you fix it feel free the re-open

**Pull request closed without merging**
