### PR TITLE
Added Icon for Trinity Trust Token

### PR DESCRIPTION
**Pull request by WorldTTT**

### CODE REVIEW

**Comment by WorldTTT** [comment]
PLEASE NOTE: the ebf87f1 was not done properly so please if you can disregard it thank you very much

**Comment by kosinusbch** [comment]
Hey, the names of the icons need to be the same as the tokenid

**Comment by WorldTTT** [comment]
Thank you for letting me know how to go about it properly and hope this is done right now

**Comment by WorldTTT** [comment]
Hello on simpleledger.info the icon still hasn't updated, I can see you have merged it thank you loads. I was just wondering why it isn't updating the icon and if you can tell me where I went wrong by anychance?  

thank you for your help

**Pull request merged**
