### PR TITLE
Added working images for SLP Bitcoin token & added Goryeo token images & SLP Sushi

### PR DESCRIPTION
**Pull request by probotnia**
Adjusted the sizes.

### CODE REVIEW

**Comment by blockparty-sh** [comment]
Hi! 

Please remove the uuid filetype images like 60e0d5ba-4414-46a3-8593-7632b7f2a8fb_200x200.png - this is just extra junk for repo since they wont be used by anything.

**Comment by probotnia** [comment]
Hi!

Will do. Couldn´t access it on the kosinus branch? Should I fork and pull
request to make it work?

to 22. huhtik. 2021 klo 5.35 Jt Freeman ***@***.***)
kirjoitti:

**Comment by kosinusbch** [comment]
Yeah, you gotta do it in your own repo. 403bd48ae4150fc17bea00f08471ec06ca5be42712cc15fa11c61e4e8e4dee61 also appears to already have been merged, so might wanna rebase as well

**Comment by kosinusbch** [comment]
Closing now for organizational reasons, feel free to re-open once issue above is resolved

**Pull request closed without merging**
