### PR TITLE
Create Kriptobi

### PR DESCRIPTION
**Pull request by zybk70**
https://tokens.bch.sx/svg/d01ec8a87409c0fe5d0af642c1f67e8a9c581478b541ee3aac4411c28e30d434

### CODE REVIEW

**Comment by kosinusbch** [comment]
@zybk70 We need icons to be perfectly square in order to merge, otherwise it would just be a cut off everything except the "rip" part of the logo

**Comment by zybk70** [comment]
https://vectr.com/tmp/asG2jkql6/b4AHQYWPd.svg?width=640&height=640&select=b4AHQYWPdpage0

**Comment by zybk70** [comment]
https://vectr.com/tmp/asG2jkql6/b4AHQYWPd.svg?width=640&height=640&select=b4AHQYWPdpage0

**Comment by zybk70** [comment]
Kriptobi

**Comment by zybk70** [comment]
Thanks for interest...I hope i did it...

**Comment by kosinusbch** [comment]
@zybk70 I meant more like you take the actual logo icon (the flaming b) and crop out the text. That's not gonna look very good on the block explorers

**Comment by zybk70** [comment]
New logo
https://vectr.com/tmp/a7A40NTFAc/d1yyzAexXF.svg?width=630&height=630&select=a7AWf18Cr&source=selection

**Comment by zybk70** [comment]
Kriptobi (3)

**Comment by kosinusbch** [comment]
Added in commit [46f8c7fb1b864c73a5039bab15ed2d9094dfd3e3](https://github.com/kosinusbch/slp-token-icons/commit/46f8c7fb1b864c73a5039bab15ed2d9094dfd3e3)

**Pull request closed without merging**
