### PR TITLE
NXH icon

### PR DESCRIPTION
**Pull request by BlackCryptoFace**
added icon for 32/64/128/original
849480f13596ce050b3e7cfec0916f5f1487a77d2d8620cced73ad9193e580ef

### CODE REVIEW

**Comment by kosinusbch** [comment]
Hey @BlackCryptoFace, I don't see an icon with that hash in that zip file

**Comment by BlackCryptoFace** [comment]
Thanks for hitting me back.
I thought I needed to the ID of token. Where can i get the hash from? I'm looking on block explorer for it and don't see it.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by BlackCryptoFace** [comment]
NXH 32, 64, 128, Original,SVG. Hope I got it right this time. :)
[slp-token-icon.zip](https://github.com/kosinusbch/slp-token-icons/files/4173667/slp-token-icon.zip)

**Comment by kosinusbch** [comment]
@BlackCryptoFace This icon seems to be really blurry and clipping off the sides, do you have one that's less corrupted?

**Comment by BlackCryptoFace** [comment]
Yeah. I have another. I’ll send it. It a version I’d drew on my iPad before.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by BlackCryptoFace** [comment]
[slp-token-icon.zip](https://github.com/kosinusbch/slp-token-icons/files/4174808/slp-token-icon.zip)

**Comment by kosinusbch** [comment]
Thanks, added to the repo. Should be live everywhere that uses the hosted endpoint now, crescent cash next icon update they do.

**Comment by BlackCryptoFace** [comment]
ok. thanks for the help. :)

**Pull request closed without merging**
