### PR TITLE
Zombie Token

### PR DESCRIPTION
**Pull request by cryptostockbook**
be8ccb8c312c2dd9aa82aa2327824fc0d54faa309b503582030fd910c4f018ca
be8ccb8c312c2dd9aa82aa2327824fc0d54faa309b503582030fd910c4f018ca
be8ccb8c312c2dd9aa82aa2327824fc0d54faa309b503582030fd910c4f018ca
be8ccb8c312c2dd9aa82aa2327824fc0d54faa309b503582030fd910c4f018ca

### CODE REVIEW

**Comment by blockparty-sh** [comment]
This has conflicts ^

**Comment by cryptostockbook** [comment]
> This has conflicts ^

Ok. What should I do? I’d like to keep this ...0fe8.png files and icon. If it’s not possible to have both, it’s ok. Thanks for Your time

**Comment by blockparty-sh** [comment]
Remove the spare token icons from this PR.

**Comment by cryptostockbook** [comment]
> Remove the spare token icons from this PR. 

Ok. but will it be still visible as spare icon (e.g. on simpleledger)?

**Comment by blockparty-sh** [comment]
Yes - don't delete them just dont add them to the PR. It might be easiest to just create a new PR only adding the zombie tokens if you don't have much experience with git.

**Comment by cryptostockbook** [comment]
> Yes - don't delete them just dont add them to the PR. It might be easiest to just create a new PR only adding the zombie tokens if you don't have much experience with git. 

Ok. Will try. Thank You

**Comment by cryptostockbook** [comment]
> Yes - don't delete them just dont add them to the PR. It might be easiest to just create a new PR only adding the zombie tokens if you don't have much experience with git. 

Sorry to bother You. I am still learning github. I created a new pull req draft and added zombie but spare was added automatically

**Comment by blockparty-sh** [comment]
NP. I just did the PR fix for you so I'm going to close this.

**Comment by cryptostockbook** [comment]
> NP. I just did the PR fix for you so I'm going to close this. 

Thank You. It’s not visible on simpleledger yet. Should I wait or do something?

**Comment by kosinusbch** [comment]
@cryptostockbook Your icon has now been added in most recent update https://simpleledger.info/#token/be8ccb8c312c2dd9aa82aa2327824fc0d54faa309b503582030fd910c4f018ca

**Comment by cryptostockbook** [comment]
> @cryptostockbook Your icon has now been added in most recent update https://simpleledger.info/#token/be8ccb8c312c2dd9aa82aa2327824fc0d54faa309b503582030fd910c4f018ca

Thank You for info and Your time

**Pull request closed without merging**
