### PR TITLE
add icon Farco Coin

### PR DESCRIPTION
**Pull request by Farco-Coin**

### CODE REVIEW

**Comment by Admin-Farco** [comment]
#347 #348 #349 #350 approve and me no ? how your working sir ?

**Comment by Admin-Farco** [comment]
is this the performance of SLP?

**Comment by Admin-Farco** [comment]
This my smart contract in Binance Smart Chain bep20 

0x0852628854e2e98279d237f3c1b7f9bdf32c87ec
https://bscscan.com/token/0x0852628854e2e98279d237f3c1b7f9bdf32c87ec

**Comment by kosinusbch** [comment]
Hey @Farco-Coin, the icons need to be named tokenid.png (txid of the transaction that created the token)

**Comment by Admin-Farco** [comment]
hey @kosinusbch that's the latest one already uses the tokenid name

**Comment by kosinusbch** [comment]
Ah alright, mind just deleting the old ones then?

**Pull request closed without merging**
