### PR TITLE
Token Logo Pepe

### PR DESCRIPTION
**Pull request by vantwembeke**

### CODE REVIEW

**Comment by kosinusbch** [comment]
The /original/ icon seems to be smaller than 128x128

**Comment by Admin-Farco** [comment]
#347  #348 #349 #350 approve and me #340 can't approve ?  is this the performance of SLP?

I check every day. and I've been waiting for days still not approved? what do you think ?

**Review by BeFrankToken — COMMENTED** [review]
Everything should be okay here.

**Comment by kosinusbch** [comment]
Hey, looks like the "original" is 64x64, original needs to be at least 128x128 @vantwembeke

**Comment by vantwembeke** [comment]
My apologies kosinusbch, i uploaded the 512x512 file again. Unsure but it is 128 on my side tho.

**Pull request merged**
