### PR TITLE
Added icon Variable Token (VAR)

### PR DESCRIPTION
**Pull request by rcallao24**
Thank you for this Sir. Keep it up!

### CODE REVIEW

**Review by rcallao24 — COMMENTED** [review]
Hello hope you can help me with this, Thank you so much :)

**Comment by rcallao24** [comment]
Hi Sir, can you help me on this? Still dnt knw why my logo havent appeared yet. Hope to hear some updates, thank u.

**Comment by kosinusbch** [comment]
Hey, looks like the /128/ icon is the same size as the original. Could you resize?

**Comment by rcallao24** [comment]
> Hey, looks like the /128/ icon is the same size as the original. Could you resize?

Ohh, have'nt notice that, sure do, thank u so much sir, I just new here even in github, just exploring and learning.. Keep up the good work sir.

**Comment by rcallao24** [comment]
> > Hey, looks like the /128/ icon is the same size as the original. Could you resize?
> 
> Ohh, have'nt notice that, sure do, thank u so much sir, I just new here even in github, just exploring and learning.. Keep up the good work sir.

Hello Sir, I updated the 128 version of icon, may I ask for you to see it please.. ty

**Comment by rcallao24** [comment]
> Hey, looks like the /128/ icon is the same size as the original. Could you resize?

Hi Sir, I already resized the icon hope you can check it, thank u.

**Comment by rcallao24** [comment]
Hello Sir, hope to hear some updates soon, thank u

**Pull request merged**
