### PR TITLE
please add

### PR DESCRIPTION
**Pull request by DIYminer**
please add

### CODE REVIEW

**Comment by damascene** [comment]
All the images are of size 64, the current commit has 64 for 32 and 64 for 128. Please fix.

**Comment by DIYminer** [comment]
Im not sure how to resize them. Those are the only sizes that the company offered  Sent from Mail for Windows From: uakSent: Thursday, February 17, 2022 11:27 PMTo: kosinusbch/slp-token-iconsCc: DIYminer; AuthorSubject: Re: [kosinusbch/slp-token-icons] please add (PR #424) All the images are of size 64, the current commit has 64 for 32 and 64 for 128. Please fix.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by damascene** [comment]
There is an error in the file name, you added (2) and (3) by mistake

**Comment by damascene** [comment]
You can use this to upload your icons in a very easy process. just upload the original and it will do the PR for you https://slp-icons.salemkode.com/

**Comment by damascene** [comment]
No response from @DIYminer

**Pull request closed without merging**
