### PR TITLE
PAF Token Icon

### PR DESCRIPTION
**Pull request by pabl0iD**

### CODE REVIEW

**Comment by kosinusbch** [comment]
Hey, could you add the "original" as well? Can be any size as long as it's 128x128 or bigger

**Comment by pabl0iD** [comment]
Hello,
thank you for reply. I just added original icon. Please let me know if everything is alright.

**Comment by Admin-Farco** [comment]
#347  #348 #349 #350 approve and me #340 can't approve ?  is this the performance of SLP?

I check every day. and I've been waiting for days still not approved? what do you think ?

**Comment by kosinusbch** [comment]
> Hello,
> thank you for reply. I just added original icon. Please let me know if everything is alright.

Hey, the "original" needs to be 1:1 (square) as well

**Comment by kosinusbch** [comment]
Added manually in https://github.com/kosinusbch/slp-token-icons/commit/bde31a5269e202c19909345d03af2bf7c4b3a867

**Pull request closed without merging**
