### PR TITLE
Iconos Monstruosos

### PR DESCRIPTION
**Pull request by ToniNFT**
Thanks for your excelent work!

### CODE REVIEW

**Comment by kosinusbch** [comment]
Hey, all photos need to be 1x1 (so if it's 32px it needs to be 32x32). If these are for NFT's, contact the creators of jungle.net to get your tokens added to all the NFT supported services.

**Comment by ToniNFT** [comment]
Thanks!

I think all icons are square except for the "original" ones, that are the real pictures.
I am new new doing this and also I do not speak english. My apologizes if I am doing somethin wrong.
Can you add the 32, 64 and 128 icons and forget the originals?

**Comment by ToniNFT** [comment]
Or do I have to do another pull-request?

**Comment by kosinusbch** [comment]
The "original" icons are what's being used for the hosted repo (tokens.bch.sx/*/tokenid.png) so they also need to be square. No need to make another PR tho, you should be able to replace the files in your local repo and they should appear in the PR

**Comment by ToniNFT** [comment]
I will.
Be proud of your patience!

**Pull request closed without merging**
