### PR TITLE
Datz add 

### PR DESCRIPTION
**Pull request by SonAndE14**
DATZ

### CODE REVIEW

**Comment by kosinusbch** [comment]
Hey @SonAndE14 did you mean to close this? Seems to be a valid pull request

**Comment by SonAndE14** [comment]
Si.. quiero verificar a DATZ y supongo que ya está completa

**Comment by SonAndE14** [comment]
Hello, sorry, could you please check this request again, since the icon does not appear in the browsers yet.

**Comment by kosinusbch** [comment]
Added manually in https://github.com/kosinusbch/slp-token-icons/commit/cca494f5736de6af0b239f9990430fe7fd0b2705

**Pull request closed without merging**
