### PR TITLE
Add Toke Icon of GRE (GREEN REX ENIGMA)

### PR DESCRIPTION
**Pull request by greenrexenigma**

### CODE REVIEW

**Comment by kosinusbch** [comment]
Looks good, but we also need one in the "original" folder (128x128 or bigger)

**Comment by greenrexenigma** [comment]
Have added 500*500 can you please check if its ok?

**Comment by kosinusbch** [comment]
Hey, the original needs to be in the "original" folder

**Comment by greenrexenigma** [comment]
Oh dear i have to be honest I'm sure how this git hub works exactly at this point, i tried to add a 500*500 You said i can add bigger but i guess i made things worse, can you just work with what you currently have ? it took me 3 days to do the whole thing right with the help of bitcoin support :/

**Comment by greenrexenigma** [comment]
95abac56596910879c1ce9a86bd2bcdbd53a02e6bf32fbd4726ee6958e48b0cd

**Comment by kosinusbch** [comment]
Added manually in https://github.com/kosinusbch/slp-token-icons/commit/8a09a0b3958201f51fbae7982fb6e1500eefc25d

**Pull request closed without merging**
