### PR TITLE
Add 3 Icons for SLP Token

### PR DESCRIPTION
**Pull request by CoincashAngel**
Add 3 Icons for SLP Token

### CODE REVIEW

**Comment by blockparty-sh** [comment]
Hi! Can you please also add file in original folder, thanks.

**Comment by bchmedia** [comment]
i added to original

**Comment by blockparty-sh** [comment]
You didn't push it up?

**Review by bchmedia — APPROVED** [review]

**Review by bchmedia — APPROVED** [review]

**Comment by bchmedia** [comment]
I WILL DO IT AGAIN

**Comment by bchmedia** [comment]
i made 2 slp token and uploaded the files

**Comment by bchmedia** [comment]
I uploaded new 8 files for 2 slp tokens and i dont know how to push it for
you
Can you help me with this?

**Comment by blockparty-sh** [comment]
Please make a new pr including original, 128, 64, 32 px version. Thanks.

**Pull request closed without merging**
